# Changes here will be overwritten by Copier
_commit: v0.1.7
_src_path: gh:dalito/linkml-project-copier
copyright_year: '2024'
create_python_classes: 'Yes'
email: philip.stroemert@tib.eu
full_name: Philip Strömert
github_org: StroemPhi
license: MIT
main_schema_class: NFDIDataset
project_description: This is an extension of the DCAT Application Profile in LinkML.
    It is intended to be used by NFDI4Chem & NFDI4Cat as a core that can further be
    extended in profiles to provide domain specific metadata for a dataset.
project_name: dcat-4C-ap
project_slug: dcat_4c_ap
use_schemasheets: 'No'

