name: Preview documentation build

on:  # yamllint disable-line rule:truthy
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:  preview-${{ github.ref }}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Python 3
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55
        with:
          python-version: 3.9

      - name: Install just & Poetry incl. plugins
        # We install poetry-dynamic-versioning into pipx because the automatic
        # install by poetry 2.x triggers a Windows issue
        # https://github.com/pypa/installer/issues/260
        # and also does not work on Ubuntu in gh-actions.
        run: |
          pipx install rust-just
          pipx install poetry
          pipx inject poetry poetry-dynamic-versioning

      - name: Install dependencies
        run: poetry install

      - name: Build documentation
        run: |
          just gen-doc
          poetry run mkdocs build

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@2fb559e4766555e23d07b73d313fe97c4f8c3cfe
        with:
          source-dir: site/
          preview-branch: gh-pages
