name: Preview documentation build

on:  # yamllint disable-line rule:truthy
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:  preview-${{ github.ref }}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Python 3
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: 3.9

      - name: Install just & Poetry incl. plugins
        # We install poetry-dynamic-versioning into pipx because the automatic
        # install by poetry 2.x triggers a Windows issue
        # https://github.com/pypa/installer/issues/260
        # and also does not work on Ubuntu in gh-actions.
        run: |
          pipx install rust-just
          pipx install poetry
          pipx inject poetry poetry-dynamic-versioning

      - name: Install dependencies
        run: poetry install

      - name: Build documentation
        run: |
          just gen-doc
          poetry run mkdocs build

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@9f77b1d057b494e662c50b8ca40ecc63f21e0887
        with:
          source-dir: site/
          preview-branch: gh-pages
